echo "==== Planar Netlist Test ====\n"
../../abc -c "lsv_cmos_dual nsp3.nmos pmos.output"
../../abc -c "lsv_cmos2sop n nsp3.nmos nmos.blif"
../../abc -c "lsv_cmos2sop p pmos.output pmos.blif"
../../abc -c "cec nmos.blif pmos.blif"
echo "\n==== Non-planar Test ====\n"
../../abc -c "lsv_cmos_dual non1.nmos pmos.output"
../../abc -c "lsv_cmos2sop n non1.nmos nmos.blif"
../../abc -c "lsv_cmos2sop n pmos.output pmos.blif"
../../abc -c "cec nmos.blif pmos.blif"
echo "\n==== Graph Gen Test ====\n"
../../abc -c "lsv_cmos_graph_gen2 test.nmos 10 0.6"

#python3 plot.py test.output
=======
#../../abc -c "lsv_cmos_dual nsp1.nmos pmos.output"
#../../abc -c "lsv_cmos2sop n nsp1.nmos nmos.blif"
#../../abc -c "lsv_cmos2sop p pmos.output pmos.blif"
#../../abc -c "cec nmos.blif pmos.blif"
#../../abc -c "lsv_cmos_dual non1.nmos pmos.output"
#echo "===== Graph Gen Test ====="
#../../abc -c "lsv_cmos_graph_gen 5 10 n test.nmos"
../../abc -c "lsv_cmos_graph_gen2 test.nmos 30 0.8"
../../abc -c "lsv_cmos_dual test.nmos test.output"
../../abc -c "lsv_cmos2sop n test.nmos test_n.blif"
../../abc -c "lsv_cmos2sop p test.output test_p.blif"
../../abc -c "cec test_n.blif test_p.blif"
cat test.nmos
cat test.output
../../abc -c "read test_n.blif; collapse; sop; print_stats -f"
